// src/components/Urls/index.tsx
"use client";

import React from "react";

export const Urls = () => {
    return (
        <div>
            <p className="flex justify-center items-center mt-4 mb-2 text-lg text-gray-200 transition-all duration-300 whitespace-nowrap">
                Yuma Ikeda / いけゆう
            </p>
            <div className="flex justify-center items-center gap-4">
                <div>
                    <a
                        target="_blank"
                        href="https://x.com/uyuyu_create"
                        className="text-gray-600 hover:text-gray-900 transition-all duration-100"
                        rel="noopener noreferrer"
                    >
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 512 512"
                            xmlSpace="preserve"
                            className="w-7 h-7 fill-current transition-all duration-100"
                        >
                            <path d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z" />
                        </svg>
                    </a>
                </div>
                <div>
                    <a
                        target="_blank"
                        href="https://github.com/ikeyu-dev"
                        className="text-gray-600 hover:text-gray-900 transition-all duration-100"
                        rel="noopener noreferrer"
                    >
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                            className="w-7 h-7 fill-current transition-all duration-100"
                        >
                            <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
                        </svg>
                    </a>
                </div>
                <div>
                    <a
                        target="_blank"
                        href="https://zenn.dev/uyuy_create"
                        className="text-gray-600 hover:text-gray-800 transition-all duration-100"
                        rel="noopener noreferrer"
                    >
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            xmlnsXlink="http://www.w3.org/1999/xlink"
                            version="1.1"
                            x="0px"
                            y="0px"
                            viewBox="0 0 88.3 88.3"
                            style={{ background: "new 0 0 88.3 88.3" }}
                            xmlSpace="preserve"
                            className="h-7 w-7 fill-current transition-all duration-300"
                        >
                            <g fill="#3EA8FF">
                                <path
                                    className="st0"
                                    d="M3.9,83.3h17c0.9,0,1.7-0.5,2.2-1.2L69.9,5.2c0.6-1-0.1-2.2-1.3-2.2H52.5c-0.8,0-1.5,0.4-1.9,1.1L3.1,81.9   C2.8,82.5,3.2,83.3,3.9,83.3z"
                                />
                                <path
                                    className="st0"
                                    d="M62.5,82.1l22.1-35.5c0.7-1.1-0.1-2.5-1.4-2.5h-16c-0.6,0-1.2,0.3-1.5,0.8L43,81.2c-0.6,0.9,0.1,2.1,1.2,2.1   h16.3C61.3,83.3,62.1,82.9,62.5,82.1z"
                                />
                            </g>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
    );
};

// frontend/components/urls.vue
<template>
    <p
        class="flex justify-center items-center mt-4 mb-2 text-lg text-gray-200 transition-all duration-300 whitespace-nowrap"
    >
        Yuma Ikeda / いけゆう
    </p>
    <div class="flex justify-center items-center gap-4">
        <div>
            <a
                target="_blank"
                href="https://x.com/uyuyu_create"
                class="text-gray-600 hover:text-gray-900 transition-all duration-100"
            >
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 512 512"
                    xml:space="preserve"
                    class="w-7 h-7 fill-current transition-all duration-100"
                >
                    <path
                        d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z"
                    />
                </svg>
            </a>
        </div>
        <div>
            <a
                target="_blank"
                href="https://github.com/ikeyu-dev"
                class="text-gray-600 hover:text-gray-900 transition-all duration-100"
            >
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    class="w-7 h-7 fill-current transition-all duration-100"
                >
                    <path
                        d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"
                    />
                </svg>
            </a>
        </div>
        <div>
            <a
                target="_blank"
                href="https://zenn.dev/uyuy_create"
                class="text-gray-600 hover:text-gray-800 transition-all duration-100"
            >
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink"
                    version="1.1"
                    x="0px"
                    y="0px"
                    viewBox="0 0 88.3 88.3"
                    style="enable-background: new 0 0 88.3 88.3"
                    xml:space="preserve"
                    class="h-7 w-7 fill-current transition-all duration-300"
                >
                    <g fill="#3EA8FF">
                        <path
                            class="st0"
                            d="M3.9,83.3h17c0.9,0,1.7-0.5,2.2-1.2L69.9,5.2c0.6-1-0.1-2.2-1.3-2.2H52.5c-0.8,0-1.5,0.4-1.9,1.1L3.1,81.9   C2.8,82.5,3.2,83.3,3.9,83.3z"
                        />
                        <path
                            class="st0"
                            d="M62.5,82.1l22.1-35.5c0.7-1.1-0.1-2.5-1.4-2.5h-16c-0.6,0-1.2,0.3-1.5,0.8L43,81.2c-0.6,0.9,0.1,2.1,1.2,2.1   h16.3C61.3,83.3,62.1,82.9,62.5,82.1z"
                        />
                    </g>
                </svg>
            </a>
        </div>
    </div>
</template>
